In [1]:
import pandas as pd
import os

In [2]:
virushost_mapping_filepath = os.path.join(os.getcwd(), "..", "..", "..", "..", "input", "data", "virushostdb", "20240129", "virushostdb_20231217.tsv")

In [3]:
virushost_mapping_filepath

'C:\\Dev\\git\\zoonosis\\src\\jupyter_notebooks\\datasets\\analysis\\..\\..\\..\\..\\input\\data\\virushostdb\\20240129\\virushostdb_20231217.tsv'

In [4]:
mapping_df = pd.read_csv(virushost_mapping_filepath, "\t")
mapping_df["host tax id"] = mapping_df["host tax id"].astype("Int64").astype("object")

C:\Users\bless\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
mapping_df

,virus tax id,virus name,virus lineage,refseq id,KEGG GENOME,KEGG DISEASE,DISEASE,host tax id,host name,host lineage,pmid,evidence,sample type,source organism
0,438782,Abaca bunchy top virus,Viruses; Monodnaviria; Shotokuvirae; Cressdnav...,"NC_010314, NC_010315, NC_010316, NC_010317, NC...",NaN,NaN,NaN,214697,Musa acuminata AAA Group,Eukaryota; Viridiplantae; Streptophyta; Strept...,17978886,Literature,NaN,NaN
1,1241371,Abalone herpesvirus Victoria/AUS/2009,Viruses; Duplodnaviria; Heunggongvirae; Peplov...,NC_018874,NaN,NaN,NaN,36095,Haliotis diversicolor,Eukaryota; Opisthokonta; Metazoa; Eumetazoa; B...,28962967,Literature,NaN,NaN
2,491893,Abalone shriveling syndrome-associated virus,Viruses; Duplodnaviria; Heunggongvirae; Urovir...,NC_011646,NaN,NaN,NaN,37770,Haliotis diversicolor aquatilis,Eukaryota; Opisthokonta; Metazoa; Eumetazoa; B...,21079776,"Literature, NCBI Virus, RefSeq",NaN,NaN
3,11788,Abelson murine leukemia virus,Viruses; Riboviria; Pararnavirae; Artvervirico...,NC_001499,NaN,NaN,NaN,10090,Mus musculus,Eukaryota; Opisthokonta; Metazoa; Eumetazoa; B...,6257398,"Literature, UniProt",NaN,NaN
4,2025595,Abisko virus,Viruses; Riboviria; unclassified Riboviria,NC_035470,NaN,NaN,NaN,201501,Epirrita autumnata,Eukaryota; Opisthokonta; Metazoa; Eumetazoa; B...,NaN,"Literature, NCBI Virus, RefSeq",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33767,3071326,Zwiesel bat bandavirus,Viruses; Riboviria; Orthornavirae; Negarnaviri...,"NC_078994, NC_078995, NC_078996",NaN,NaN,NaN,59451,Eptesicus nilssonii,Eukaryota; Opisthokonta; Metazoa; Eumetazoa; B...,NaN,RefSeq,NaN,NaN
33768,253701,Zygocactus virus X,Viruses; Riboviria; Orthornavirae; Kitrinoviri...,NC_006059,NaN,NaN,NaN,3594,Schlumbergera,Eukaryota; Viridiplantae; Streptophyta; Strept...,15098106,Literature,NaN,NaN
33769,114871,Zygosaccharomyces bailii virus Z,Viruses; Riboviria; Orthornavirae; Pisuviricot...,NC_003874,NaN,NaN,NaN,4932,Saccharomyces cerevisiae,Eukaryota; Opisthokonta; Fungi; Dikarya; Ascom...,NaN,Literature,NaN,NaN
33770,114871,Zygosaccharomyces bailii virus Z,Viruses; Riboviria; Orthornavirae; Pisuviricot...,"NC_003874, NC_075420",NaN,NaN,NaN,4954,Zygosaccharomyces bailii,Eukaryota; Opisthokonta; Fungi; Dikarya; Ascom...,NaN,"Literature, RefSeq",NaN,NaN
33771,2501222,Zymoseptoria tritici fusarivirus 1,Viruses; Riboviria; Orthornavirae; Pisuviricot...,NC_076668,NaN,NaN,NaN,1047171,Zymoseptoria tritici,Eukaryota; Opisthokonta; Fungi; Dikarya; Ascom...,NaN,RefSeq,NaN,NaN

In [39]:
mapping_df["virus tax id"].value_counts()

12282      41
10243      31
89471      31
12271      25
268331     24
           ..
1923195     1
1923194     1
1923193     1
1923192     1
2501222     1
Name: virus tax id, Length: 28782, dtype: int64

In [40]:
mapping_df["host tax id"].value_counts()

1          2367
246196     1727
9606       1486
562        1034
573         665
           ...
1089748       1
1158105       1
2247          1
2801032       1
1047171       1
Name: host tax id, Length: 4787, dtype: int64

In [17]:
mapping_df[["virus name", "virus tax id", "host tax id"]].groupby(["virus name", "virus tax id"]).count().sort_values("host tax id", ascending=False)

                                                  host tax id
virus name                          virus tax id
Tobacco ringspot virus              12282                  41
Melon yellow spot virus             89471                  31
Cowpox virus                        10243                  31
Arabis mosaic virus                 12271                  25
Maize streak virus - E[Pat]         268331                 24
...                                                       ...
Antarctic microvirus CAA_003_V_9    2664229                 0
Antarctic microvirus CAA_003_V_4    2664228                 0
Antarctic microvirus CAA_003_V_1    2664227                 0
Stx2a-converting phage Stx2_PV03-14 2816181                 0
uncultured virus                    340016                  0

[28782 rows x 1 columns]

              host tax id
virus tax id
12282                  41
10243                  31
89471                  31
12271                  25
268343                 24
...                   ...
2864076                 0
2864075                 0
2864074                 0
2864073                 0
2929331                 0

[28782 rows x 1 columns]